# Generated by Django 5.1.1 on 2024-09-12 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customerOrder', '0002_alter_order_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total',
        ),
    ]
